### ISSUE TITLE
Dark Theme makes it difficult to read incoming review categories list which uses dark text on dark background

### ISSUE THREAD

**Issue by vijaysitaram** [ni/reviewboard-userscripts#3]
The dark theme uses a midnight blue / inky color but the categories view in the RB dashboard for what review groups you belong to are still rendered in black, so they are almost impossible to read as dark text on a dark background unless you zoom way in.
## Screenshots

Screenshot has group names censored, but the Incoming categories "Open" and "To Me" show the problem just as well. Not sure why we have weird negative counts in some cases but I don't believe it's anything to do with this userscript.

![image](https://user-images.githubusercontent.com/66134815/83355720-ed16ca80-a326-11ea-8fe6-18769b31a224.png)

## Logs

If applicable, add any relevant messages or errors you see in the browser's JavaScript console.
N/A

## Context

- Extension Version: 1.1.2
- Browser: Firefox 76.1
- URL: outgoing RB dashboard

**Comment by alejandro5042** [comment]
Thanks for reporting this! You're right -- the styling is off.

Please verify that it is fixed in latest version. (You can force an update by your userscript extension manager settings or extension dropdown.)

**Comment by vijaysitaram** [comment]
The group names being printed in white and a bright enough red definitely helps their readability on dark theme. But the numbers and links at the top (My Dashboard, New Review Request, ... Hide archived) are trickier in some cases:

- Dark Theme: One of my monitors at home they look OK because it has high brightness and contrast through a variety of display angles. But on my other monitor, the purple/blue blends too closely into the background.

- Middle Theme: The red numbers for the review quantity is difficult to read on the either monitor, but actually slightly worse on my brighter monitor. The links at top are significantly harder to read on my dimmer monitor because the purple/blue has poor contrast against the dimmer purplish background, especially when I'm off a little on vertical viewing angles (it's not quite as bad on a bright monitor).

What do you think about tweaking those links and even the red text in both cases to something more white or golden?

![image](https://user-images.githubusercontent.com/66134815/83363453-2b2fe080-a35f-11ea-9854-cb2a0569f0fd.png)

**Comment by alejandro5042** [comment]
Please update and verify that the golden text looks better for you!

**Comment by vijaysitaram** [comment]
It's definitely more readable, thank you. On the original theme, zero counts were shown as a gray so they blended in to the background and only the non-zero red numbers were then prominent against the background. Is that something easy to do here as well? You can still see this in the light theme as well.

Here's the difference in the rendered HTML between a zero-count where it's gray:
```
<li class="item has-url has-count new-subsection" onclick="javascript:window.location=&quot;/dashboard/?group=GROUPNAME&amp;view=to-group&quot;; return false;">
 <div class="page-sidebar-row">
  <div class="rb-icon "></div>
  <span class="label"><a href="/dashboard/?group=GROUPNAME&amp;view=to-group">GROUPNAME</a></span>

  <span class="count count-zero">0</span>

 </div>
</li>
```
vs. a non-zero acount ("active") where it uses red text in the light theme:
```
<li class="item has-url active has-count" onclick="javascript:window.location=&quot;/dashboard/?group=GROUPNAME2&amp;view=to-group&quot;; return false;">
 <div class="page-sidebar-row">
  <div class="rb-icon "></div>
  <span class="label"><a href="/dashboard/?group=GROUPNAME2&amp;view=to-group">GROUPNAME2</a></span>

  <span class="count ">4</span>

 </div>
</li>
```
